In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [17]:
df=pd.read_excel('/content/dataKasus-1.xlsx')

In [18]:
df.head(20)

,NO,NAMA,USIA,PARITAS,JARAK KELAHIRAN,RIW HIPERTENSI,RIW PE,OBESITAS,RIW DM,RIW HIPERTENSI/PE DALAM KELUARGA,SOSEK RENDAH,PE/Non PE,Unnamed: 12
0,1,NAMA 1,23 TH,3,< 2 tahun,Tidak,Tidak,Tidak,Ya,Tidak,>UMR,Non PE,NaN
1,2,NAMA 2,29 TH,2,< 2 tahun,Tidak,PEB,Tidak,Tidak,Ada,>UMR,PE,NaN
2,3,NAMA 3,20 TH,1,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
3,4,NAMA 4,18 TH,1,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
4,5,NAMA 5,34 TH,3,> 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
5,6,NAMA 6,28 TH,3,< 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
6,7,NAMA 7,36 TH,4,> 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
7,8,NAMA 8,28 TH,2,> 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
8,9,NAMA 9,39 TH,4,< 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
9,10,NAMA 10,37 TH,3,> 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
10,11,NAMA 11,16,0,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
11,12,NAMA 12,24 TH,1,anak pertama,Ya,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,HT gestasional
12,13,NAMA 13,31 TH,3,< 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
13,14,NAMA 14,35 TH,3,> 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
14,15,NAMA 15,28 TH,2,< 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
15,16,NAMA 16,13 TH,1,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
16,17,NAMA 17,21 TH,1,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
17,18,NAMA 18,36 TH,3,> 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
18,19,NAMA 19,40 TH,3,> 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
19,20,NAMA 20,23 TH,2,< 2 tahun,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN

In [19]:
print(df.head())

   NO    NAMA   USIA  PARITAS JARAK KELAHIRAN RIW HIPERTENSI RIW PE OBESITAS  \
0   1  NAMA 1  23 TH        3       < 2 tahun          Tidak  Tidak    Tidak
1   2  NAMA 2  29 TH        2       < 2 tahun          Tidak    PEB    Tidak
2   3  NAMA 3  20 TH        1    anak pertama          Tidak  Tidak    Tidak
3   4  NAMA 4  18 TH        1    anak pertama          Tidak  Tidak    Tidak
4   5  NAMA 5  34 TH        3      > 2 tahun           Tidak  Tidak    Tidak

  RIW DM RIW HIPERTENSI/PE DALAM KELUARGA SOSEK RENDAH PE/Non PE Unnamed: 12
0     Ya                            Tidak         >UMR    Non PE         NaN
1  Tidak                              Ada         >UMR        PE         NaN
2  Tidak                            Tidak         >UMR    Non PE         NaN
3  Tidak                            Tidak         >UMR    Non PE         NaN
4  Tidak                            Tidak         >UMR    Non PE         NaN

In [20]:
df.columns = ['NO', 'NAMA', 'USIA', 'PARITAS', 'JARAK KELAHIRAN', 'RIW HIPERTENSI', 'RIW PE', 'OBESITAS', 'RIW DM',
              'RIW HIPERTENSI/PE DALAM KELUARGA', 'SOSEK RENDAH', 'PE/Non PE', 'Unnamed: 12']

In [21]:
df = df.drop_duplicates()

In [22]:
df.loc[data['USIA'].isnull()]

,NO,NAMA,USIA,PARITAS,JARAK KELAHIRAN,RIW HIPERTENSI,RIW PE,OBESITAS,RIW DM,RIW HIPERTENSI/PE DALAM KELUARGA,SOSEK RENDAH,PE/Non PE,Unnamed: 12
99,101,NAMA 100,NaN,1,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
100,102,NAMA 101,NaN,1,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN
262,264,NAMA 263,NaN,1,anak pertama,Tidak,Tidak,Tidak,Tidak,Tidak,>UMR,Non PE,NaN

In [23]:
df['PE/Non PE'] = df['PE/Non PE'].replace({'PE': 1, 'Non PE': 0})

In [24]:
print(df.describe())

               NO     PARITAS
count  561.000000  561.000000
mean   281.859180    1.709447
std    162.301009    1.012105
min      1.000000    0.000000
25%    142.000000    1.000000
50%    282.000000    2.000000
75%    422.000000    2.000000
max    562.000000    6.000000

In [25]:
df.to_excel('dataKasus-1_cleaned.xlsx', index=False)

In [28]:
from google.colab import files
files.download('dataKasus-1_cleaned.xlsx')